// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://belrumdjnpwghdykdtob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlbHJ1bWRqbnB3Z2hkeWtkdG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTc4MjMsImV4cCI6MjA2ODY3MzgyM30.gXphDSwmkWJJWFeK2EjoBecznHX-ipTTkQd9Uggocc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});